pictures: pictureInsert
Allow User Abort [ Off ]
Set Error Capture [ On ]
If [ reference::picture ≠ "" and reference::lock = "" ]
Show Custom Dialog [ Message: "Replace current picture?"; Buttons: “Cancel”, “OK” ]
If [ Get ( LastMessageChoice ) = 1 ]
Go to Field [ ]
Exit Script [ ]
Else If [ Get ( LastMessageChoice ) = 2 ]
Go to Field [ reference::picture ]
Insert Picture [ ]
Go to Field [ ]
End If
Else If [ testlearn::Picture ≠ "" ]
Show Custom Dialog [ Message: "Replace current picture?"; Buttons: “Cancel”, “OK” ]
If [ Get ( LastMessageChoice ) = 1 ]
Go to Field [ ]
Exit Script [ ]
Else If [ Get ( LastMessageChoice ) = 2 ]
Go to Field [ testlearn::Picture ]
Insert Picture [ ]
Go to Field [ ]
End If
Else If [ testlearnReportTags::Picture ≠ "" ]
Show Custom Dialog [ Message: "Replace current picture?"; Buttons: “Cancel”, “OK” ]
If [ Get ( LastMessageChoice ) = 1 ]
Go to Field [ ]
Exit Script [ ]
Else If [ Get ( LastMessageChoice ) = 2 ]
Go to Field [ testlearnReportTags::Picture ]
Insert Picture [ ]
Go to Field [ ]
End If
Else If [ testlearnReportTags::Picture = "" ]
Show Custom Dialog [ Message: "Select a picture to insert."; Buttons: “Cancel”, “OK” ]
If [ Get ( LastMessageChoice ) = 1 ]
Go to Field [ ]
Exit Script [ ]
Else If [ Get ( LastMessageChoice ) = 2 ]
Go to Field [ testlearnReportTags::Picture ]
Insert Picture [ ]
Go to Field [ ]
End If
Else If [ Get ( LayoutTableName ) = "test" ]
If [ groupTest::testReportPicture = "" ]
Go to Field [ groupTest::testReportPicture ]
Insert Picture [ ]
Go to Field [ ]
Exit Script [ ]
End If
Show Custom Dialog [ Message: "Replace current picture or delete it?"; Buttons: “Cancel”, “replace”, “delete” ]
If [ Get ( LastMessageChoice ) = 1 ]
Go to Field [ ]
Exit Script [ ]
Else If [ Get ( LastMessageChoice ) = 2 ]
Go to Field [ groupTest::testReportPicture ]
Insert Picture [ ]
Go to Field [ ]
Else If [ Get ( LastMessageChoice ) = 3 ]
Set Field [ groupTest::testReportPicture; "" ]
Go to Field [ ]
End If
End If
#
#
January 7, 平成26 17:04:55 Imagination Quality Management.fp7 - pictureInsert -1-
